version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      backend: { aliases: [ postgres.backend ] }

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tcsinvest/app
    networks:
      backend: { aliases: [ app.backend ] }

  notebook:
    image: jupyter/tensorflow-notebook
    environment:
      JUPYTER_TOKEN: roma
    volumes:
      - ./jupyter:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      backend: { aliases: [ notebook.backend ] }

networks:
  backend:
    driver: bridge

volumes:
  postgres-db-data:
  jupyter-data:
