spring:
  application:
    name: tkinvest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
tinkoff:
  starter:
    apiToken:
      fullAccess: <put-api-token-here>
